# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1fba73ee32238e4c0b9b643546ed868e56c79411ee2cec2933ad33ad28924b3656ae77e3e7cd95eb31704fd9b9e517b51b717d23fb4b9fb62b9b684e0a91bbc9

test:
  secret_key_base: 1b2cf72a8cb11ec5deff4c4ecec376227d85bb0351df6f0aa9b7c243ba019fa8db30348731cef19537c388d56a450da59e6549a8c5534252187f056a2bd53c63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
